# Generated by Django 5.2.4 on 2025-07-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_link_llink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lLink',
            new_name='Link',
        ),
    ]
